#+Title: Virtual 40hr CORE Syllabus
* Forty Hour CORE: Syllabus
** About this Course
   :PROPERTIES:
   :CUSTOM_ID: about-this-course
   :END:

First, *welcome*.

You are about to begin something new. Part of any new job is learning new skills, ideas and perspectives. Working as a Direct Support Professional (DSP) you will need all of the knowledge and skills you can acquire. The DDA Forty Hour CORE, commonly referred to as the 40 hour or 40hr, is intended to help you learn all of the essential elements of your position.

This course will not teach you everything you need to know as a DSP. That requires time and real experience working with people with intellectual and developmental disabilities. The 40hr course helps provide a foundation of knowledge and skill to build from, as well as the basic credentials you need to work in this field.

The 40hr is broken into chapters that cover different topics and ideas. Here is a list:

- Chapter 1: Direct Support Professional's Role (DSP Role)
- Chapter 2: Overview of Developmental Disabilities
- Chapter 3: Residential Guiding Values and Individual Services
- Chapter 4: Intro to Positive Behavior Support Plans
- Chapter 5: Effective Communication
- Chapter 6: Habilitation Skills
- Chapter 7: IISP & Support Plans
- Chapter 8: Nutrition and Dietary Guidelines
- Chapter 9: Healthcare and Health Management
- Chapter 10: Medication Management
- Chapter 11: Emergency Preparedness
- Chapter 12: Skills Acquisition and Support (Personal Care)
- Chapter 13: Confidentiality (HIPAA)
- Chapter 14: Mandated Reporting

Chapters take anywhere between one to four hours to complete and result in about forty hours of learning time in total.

*** Timeframes

**** Mandatory Orientation
     In order to participate in this course you must attend a virtual orientation. See your welcome email for the link and time. If are not able to attend you must notify your supervisor and the instructors (contact information below) and arrange an alternate time and method.

This course runs for three weeks, with some additional time available at the end. There are rolling due dates with new chapters assigned at the beginning of each week. See below for a table outlining chapter assignment and due dates:

**** Chapter Opening and Due Dates
| *Chapter*                                                     | *Chapter Opened* | *Chapter Due*  | *Estimated Hours to Complete* | *Required for Exempt Staff* |
|---------------------------------------------------------------+------------------+----------------+-------------------------------+-----------------------------|
| Chapter 1: Direct Support Professional's Role (DSP Role)      | May 5th, 2021    | May 12th, 2021 |                           2.5 |                             |
| Chapter 2: Overview of Developmental Disabilities             | May 5th, 2021    | May 12th, 2021 |                             2 |                             |
| Chapter 3: Residential Guiding Values and Individual Services | May 5th, 2021    | May 12th, 2021 |                           2.5 |                             |
| Chapter 4: Intro to Positive Behavior Support Plans           | May 5th, 2021    | May 14th, 2021 |                             4 |                             |
| Chapter 13: Confidentiality (HIPAA)                           | May 5th, 2021    | May 14th, 2021 |                             2 | *                           |
| Chapter 14: Mandated Reporting                                | May 5th, 2021    | May 14th, 2021 |                           1.5 | *                           |
| Estimated Hours Set #1                                        | 14.5             |                |                               |                             |
| Chapter 5: Effective Communication                            | May 12th, 2021   | May 19th, 2021 |                             4 |                             |
| Chapter 6: Habilitation Skills                                | May 12th, 2021   | May 19th, 2021 |                           1.5 |                             |
| Chapter 7: IISP & Support Plans                               | May 12th, 2021   | May 19th, 2021 |                             2 |                             |
| Chapter 8: Nutrition and Dietary Guidelines                   | May 12th, 2021   | May 21st, 2021 |                             4 |                             |
| Chapter 11: Emergency Preparedness                            | May 12th, 2021   | May 21st, 2021 |                             3 | *                           |
| Estimated Hours Set #2                                        | 14.5             |                |                               |                             |
| Chapter 12: Personal Care Online Components                   | May 19th, 2021   | May 28th, 2021 |                             6 |                             |
| Chapter 9: Healthcare and Health Management                   | May 19th, 2021   | May 28th, 2021 |                             4 |                             |
| Chapter 10: Medication Management                             | May 19th, 2021   | May 28th, 2021 |                           2.5 | *                           |
| Chapter 12: Personal Care Skills Lab Components               | May 19th, 2021   | May 28th, 2021 |                             2 |                             |
| Estimated Hours Set #3                                        | 14.5             |                |                               |                             |

The skills lab portion of Chapter 12: Personal Care requires an in person component. Details depend on your location, lab availability and will be released along with the Chapter 12 course.

Each set of chapters released should be completed by their due date. However, incase this is not possible, a grace period of one week after these dates will be shown to students who are clearly working to complete material and are actively communicating with their instructors. See expectations below for more information.

Before the start of class, please complete the short Before Class section that is available to you on sign in. The getting started section provides your instructor with some individual information but also gives you a chance to practice within the platform.

*** Note for Exempt Staff

Exempt staff are new staff to VOAWW who hold credentials that exempt them from needing to complete the full 40hr CORE upon hire. Some examples of credentials that offer exemption include a 40/75hr certificate from another agency, HCAC, CNA/NAC, and select others. While exempt from completing all classes, exempt staff must still complete some fundamental courses to ensure full understanding of expectations, policy and procedure. These classes are indicated above in the final column. Additional VOAWW specific classes will be required as they become available.

Students from outside VOAWW should consult their supervisors regarding their exemption status and current credentials.

# *** Personal Care Skills Labs
#     Chapter 12: Personal Care is currently the only chapter with an in-person component. Below is a preview of the dates and times you will be able to sign up for to complete this skills lab. Please note that all time begin with two slots open and will be filled on a first come, first serve basis. If you have a specific time/date you can commit to now please email training@voaww.org with the title "November Skills Lab Signup". Otherwise we will send out reminders and signups when Chapter 12 is initially released online. Please let us know as soon as possible if none of these dates/times will work for you as well.

#     The skills lab can be completed in roughly one hour with time at the beginning and end for a short briefing on the lab and COVID-19 safety as well as sanitizing/cleaning. Please arrive a little before your time slot to ensure timely completion.

#    | Start Times | 12/2       | 12/3       | 12/4           |
#    | 9:00 am     | Open, Open | Open, Open | Open, Open     |
#    | 10:15 am    | Open, Open | Open, Open | Open, Open     |
#    | 11:30 am    | Open, Open | Open, Open | Open, Open     |
#    | 1:15 pm     | Open, Open | Open, Open | Open, Open     |
#    | 2:30 pm     | Open, Open | Open, Open | Closed, Closed |
#    | 3:45m       | Open, Open | Open, Open | Closed, Closed |

** Expectations

As a DSP you are expected to act independently and with good judgement. This course expects the same. This document lays out the timelines and expectations for completion and leaves both in your hands. Your instructors will be keeping up with your progress as well as interacting with you throughout the course. They are also available to answer questions and help with any problems you encounter.

*** Expectations of You

*You are expected complete your work on time.* If you anticipate not being able to meet your deadlines you must communicate this ahead of the deadline to your instructors. It is your responsibility to make sure your message is received and understood. As stated above, a grace period will be extended one week after the due date for students who are actively working towards completion and communicating with instructors. If you do not communicate prior to the deadline, or you have exceeded the one week period, the instructor will communicate this to the relevant supervisor for follow up. Exceptional circumstances will be evaluated on a case by case basis.

*You are expected to do the work.* This means that you read the instructions given, ask questions and attempt to complete all components of the class to the best of your ability. Your progress and completion will be tracked both through the system automatically as well as by your instructors.

*You are expected to participate.* A number of the discussions within this course are intended to create a conversation. This means that you will need to not only post your answer but reply to those of others. Not replying to others is the most common reason a discussion activity remains incomplete for a student. See below for our forum policies for additional guidelines.

** Forum Guidelines

When posting in a discussion forum, whether as an activity or asking a general question, please follow these guidelines and expectations.

*** Interacting with Others
    :PROPERTIES:
    :CUSTOM_ID: interacting-with-others
    :END:

Above all, you are expected to be kind, helpful, and respectful. Assume the best of people and try to help them feel included and valued. If you know the answer to a question, give it! If you want to be a part of a conversation, join it! Just make sure you are kind, helpful, and respectful in how you do it.

*** Forums as Activities
    :PROPERTIES:
    :CUSTOM_ID: forums-as-activities
    :END:

Some of the discussion boards/forums are for activities. When this is the case please keep discussions on the topic. There is a general discussion forum in the main course where you can post questions or talk about other topics. Off-topic discussions in activity forums may be removed.

*** Work
    :PROPERTIES:
    :CUSTOM_ID: work
    :END:

Please remember that these courses are being completed for work. Keep it work appropriate and ensure that what you post reflects well on you and your organization.

*** HIPAA
    :PROPERTIES:
    :CUSTOM_ID: hipaa
    :END:

No information that may be protected by HIPAA should be posted in forums or on dstrainings.com. If you have specific client-related questions, please send a message directly to an instructor or your supervisor.

** In Case of Trouble

Are you having trouble logging into dstrainings.com? Did you forget your password? Can't figure out what you're supposed to do next?

Your answers to all of these questions and any others you may have can be found by sending an email to training@voaww.org. Please make sure when you email to indicate your full name and a clear explanation of your problem or question. Please remember that your learning is /your/ responsibility. If you encounter any barriers to successfully learning and completing the course, please do not hesitate to reach out. You instructors are available to help. You can expect a reply to your email within one (1) business day or less.

If you have questions about class content, please use the discussion board at dstrainings.com to ask your question. Either an instructor or fellow student will probably have an answer or point you in the right direction, and others will be able to learn from it as well. Anything regarding technology challenges or a personal barrier to completion, or that may involve sensitive or confidential information should be resolved through email.

** Meet your instructors
   :PROPERTIES:
   :CUSTOM_ID: meet-your-instructors-1
   :END:

While you will get to know them better as you move through the 40hr CORE, below are short descriptions of your instructors for the course.

*** Matthias Austin

Matthias has been teaching others for nearly a decade. As a Master Trainer he instructs staff members with VOAWW, develops new curriculum for internal and external participants and conducts Train the Trainers for new 40hr CORE instructors on behalf of DDA. Matthias and his wife have two cats, Ziggy and Hawkeye, and a dog named Data. They may make appearances in any live sessions like office hours.

# *** Abby Schoppen

# Abby has been teaching others for nearly two decades and has been performing NAC/CNA/DSP work for more than two decades, all in a variety of settings. As a Master Trainer she instructs staff members with VOAWW, develops new curriculum for internal and external participants and conducts Train the Trainers for new 40hr CORE instructors on behalf of DDA. Abby and her husband have two daughters and three cats. They may also make appearances in any live sessions like office hours.

** Helpful Information 
 
*** Logging In
    Your user name is typically your first initial, a period, then your last name. So, John Doe's username is "j.doe".
    Your password for first time entry is "Pass2020!".
    If you're ever having trouble getting in, please reach out to training@voaww.org for help.

*** "I'm running late, now what?"
    If you find yourself running behind, please let the instructors know at training@voaww.org. In general grace will be extended. It is important to complete the majority of work within the month the trainings start, but we know life happens and are here to support you.

*** "I am having trouble with my internet, computer, etc."
    While we can help troubleshoot certain issues, a working device, browser and internet connection are required to complete these trainings. If you are having trouble with one of these things, please reach out to us and/or your supervisor to troubleshoot the issue. 
