Hello {{name}},

Welcome to KeyMakers! Over the next nine months we will be working together on understanding and growing our selves, teams and program.

Our first session is this comming Wednesday (9/7) from 9:00 am to 4:00 pm in the Saparto (Everett) Office. There will be snacks and light refreshments as well as an hour long break to eat/grab lunch. I've included our agenda below. I will also be sending out calendar invites for the rest of our sessions so they are on your calendar moving forward.

Before our first session please complete the enneagram personality quiz. It is important that this is finished before our session on Wednesday! While going through the assessment, be sure to think beyond just your work life and be honest with yourself about your own strengths and challenges. It is easy on assessments like this to answer based on how you wish you were, rather than how you think, feel or act in reality. In order to unlock greater self-awareness, we start by being honest with ourselves.

Link: {{link}}

*** KeyMakers Sessions 1 Agenda: Wednesday 9/7

- 9:00  AM 	Welcome
- 9:10  AM 	Reflection
- 9:20  AM  Introductions
- 9:30  AM 	Establishing Norms or Rules of Engagement
- 10:00 AM	Break
- 10:15 AM	Getting Warmed Up: What is Leadership?
- 11:00 AM	KeyMakers Background, Organizing Principles, Program Components
- 12:00 PM	Lunch
- 1:00  PM 	Personality Assessment Discussion
- 3:45  PM 	Quiet Reflection on the Day’s Learning
- 4:00  PM 	Wrap up and Closing


Please reach out with any questions!

{{signature}}
