Hello {name},

You have been signed up for our December Peer Coaching class. This class will be virtual and will require some on the job work between its two zoom sessions.

*** Before Class
    - Briefly review the documents attached to this message
    - Think of a goal you'd like to work on, either personal or work related, to plan for during class.
    - *Make a plan for our live class times, on Tuesday 12/7 and Wednesday 12/15, so you can give your full attention to our times together*.

*** Live (Zoom) Classes
    We will meet for class together twice, via zoom. The dates, times and links to join can be found below:

**** Tuesday, December 7th
     Start time: 10:00 am
     End Time: 2:00 pm
     
**** Wednesday, December 15th
     Start time: 10:00 am
     End Time: 1:00 pm

**** Zoom link for both sessions: https://us02web.zoom.us/j/88446034838
     
Please come prepared to participate and be seen and heard by the rest of the class. This course includes group discussions and breakout rooms.

After reviewing the material attached to this message, please reach out to your supervisor if you'd like a printed copy. I've asked they be ready to make one available to you. Contact them before Friday if that is the case.

If you have any questions please reply to this email!

{signature}
