* Day 1 Morning
Good Morning {{name}},

This email is a reminder that the Virtual 40hr Train the Trainer's first class is starting in about 1 hour at 10:00 am.

Link is included here:

Please let me know if you have any questions ahead of our start time and come ready to give your full attention and participation!

See you soon,

{{signature}}

* Day 1 EOD
Hey {{name}},

Thank you for joining us today for the start of our TTT course. Just as a reminder of what should be completed ahead of our start time tomorrow at 10:00 am:

- Chapter 1 & 2 reviews posted to www.dstrainings.com (should already be completed and posted, but complete if not)
- Link to first recording, with self-reflection, submitted 
- Discussion questions answered
- Skimm Chapters 3 & 4 (Don't fully read, just skim!)
- Read over Trainer Tips #1
   
All the detailed instructions can be found under the Day 1 section @ www.dstrainings.com (link)

* Day 2 Morning

 Good Morning {{name}},

 This is just a reminder that we will be starting our second class day in about 1 hour. Link included below.

 See you soon!

 {{signature}}

* Day 2 EOD
Hey {{name}},

Thank you for joining us today for the start of our TTT course. Just as a reminder of what should be completed ahead of 10:00 am tomorrow:

- Chapter 3 & 4 reviews posted to www.dstrainings.com (should already be completed and posted, but complete if not)
- Record a teachback from chapter 3 or 4 and post the link (detailed instructions online)
- Brief Feedback to your partner's video recording.
- Discussion questions answered
- Skimm Chapters 5 & 6 (Don't fully read, just skim!)
- Read over Trainer Tips #2
   
All the detailed instructions can be found under the Day 2 section @ www.dstrainings.com (link)

As discusssed at the end of class today, Day 3 is the start of a slightly new pattern of how class will run. Below is a summary, but please reach out if you have any questions!

Day 3

- Complete independent reviews for chapters 5 & 6, posting the results of the review activities.
- Do a teachback with your small group at the time you agreed on during class.
- Record a teachback from chapters 5 & 6 and post by the end of the day
- Meet with the whole group from 3:00 pm to 4:00 pm ()


* Day 4 Recap/Reminders
  Hey all,

  Below is a recap of what you should have complete today:
  
- Read through the materials for Chapters 8 & 9 and complete the review activities. Results can be posted online.
- Meet with your group and do some teachbacks from the today’s chapters. Remember to pick a section or activity from each chapter and try not to repeat them in your group. 
- Record a teachback from today’s chapters and post online. Give some feedback to a recorded teachback from your small group as well. Make sure everyone gets some feedback!
- Complete the end of day discussion questions.

  Day 5 (Friday)

  Our last day this week is a little different than the others. All of you have been puttin in a ton of work this week, both for this class and in many cases other areas of your job as well.

  Friday we are just doing two things:
  - Independent review of Chapter 7
  - Meet in your small group to do one teach back each from the chapter and give some feedback.

  We will not have an afternoon check in, recorded teachback or any discussion questions. If you are missing any of the work required so far, like your chapter reviews, recorded teachbacks or discussion question responses, please make sure these get uploaded and one before we meet on Monday.

  Day 6 (Monday)

  We'll be covering Chapters 10 and 11 and it will mirror our normal pattern. I'll send a reminder out Monday morning with more information!

  I hope everyone has a great weekend, and don't hesitate to reach out with any questions!

  
* Day 5 Reminders
  Good Morning all,

  This message is just a quick reminder for you on what is happening today:
  - Complete your review of chapter 7 and post the results of your review activity.
  - Meet with your small group at the agreed on time. Please don't forget to schedule your meeting time for Monday during this time as well!

    That's it!

    If you have any work you're still finishing from earlier in the week please make sure that gets finished before Monday. Otherwise, have a fantastic weekend!

    Reach out with any questions you have!
  
* Day 6 Summary
  Good Morning Everyone!

  I hope you had a good weekend.

  Today we are working on chapters 10 and 11. We'll use the same pattern as before. I've outlined it again below:

 - Read through the materials for Chapters 10 & 11 and complete your review activities. Results should be posted online.
 - Meet with your group and do some teachbacks from the today’s chapters.
 - Meet all together between 3:00 pm and 4:00pm. Zoom Link: https://us02web.zoom.us/j/83241742428
 - Record a teachback from today’s chapters and post online.
 - Complete the end of day discussion questions.

* Day 6 Recap

  Hello all,

  Just a reminder of what should get finished today and a couple reminders:
  
 - Read through the materials for Chapters 10 & 11 and complete your review activities. Results should be posted online.
 - Meet with your group and do some teachbacks from the today’s chapters.
 - Record a teachback from today’s chapters and post online.
 - Complete the end of day discussion questions.

   
* Day 7 Summary
  Good Morning All,
  
  Today we are working on chapters 13 and 14. We'll use the same pattern as before. I've outlined it again below:

 - Read through the materials for Chapters 10 & 11 and complete your review activities. Results should be posted online.
 - Meet with your group and do some teachbacks from the today’s chapters.
 - Meet all together between 3:00 pm and 4:00pm. Zoom Link: https://us02web.zoom.us/j/83241742428
 - Record a teachback from today’s chapters and post online.
 - Complete the end of day discussion questions.

 Please also talk to your co-workers in the class (i.e. you all work at the same company) and let me know a time we can meet on Wednesday ahead of our check-in at 3 pm. We'll take about a half hour per group. 

 
* Day 8 Summary

* Day 8 Recap/Reminder
  Hey all,

  This is just a quick reminder of what we're doing today and when we're scheduled to start tomorrow.
  
  Reminder:

  No afternoon checkin today. You should spend this time finishing any outstanding work (chapter reviews, recordings, discussions, etc), prepare for Trainer Idol, and finish/submit your Asynchronous class plan. You might want to rehearse for your Trainer Idol teachback with someone from one of your small groups, though totally optional.

  Teachbacks should be planned wrap up after about 5 minutes and don't forget to practice how you're going to actually present it on the day!

  We will meet together again Friday at 10:00 am. I'll be available for questions or to just talk from 9:15 onwards in the same Zoom link as usual. 

  Let me know if you have any questions!
